version: '3.8'

networks:
  loki:

services:
  mysql:
    image: mysql:latest
    hostname: hostname-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdasd123
      MYSQL_DATABASE: dev_food
      MYSQL_USER: food
      MYSQL_PASSWORD: asdasd123
    volumes:
      - mysql_data:/var/lib/mysql
  loki:
      image: grafana/loki:latest
      ports:
        - "3100:3100"
      volumes:
        - ./loki-config.yaml:/mnt/loki/loki-config.yaml  # 현재 경로의 설정 파일을 컨테이너 내로 마운트
      command: -config.file=/mnt/loki/loki-config.yaml
      networks:
        - loki

  promtail:
      image: grafana/promtail:latest
      volumes:
        - /Users/mac/project/food-recommendation/logs:/mnt/logs
        - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      command: -config.file=/mnt/config/promtail-config.yaml
      networks:
        - loki

  grafana:
      image: grafana/grafana:master
      ports:
        - "3000:3000"
      networks:
        - loki
volumes:
  mysql_data:

