server:
  http_listen_port: 3100
  grpc_listen_port: 0

positions:
  filename: /logs/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: info
    static_configs:
      - targets:
          - localhost
        labels:
          job: info_logs
          __path__: /logs/info.log
  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: error_logs
          __path__: /logs/error.log
  - job_name: warning
    static_configs:
      - targets:
          - localhost
        labels:
          job: warning_logs
          __path__: /logs/warning.log
  