server:
  http_listen_port: 3100
  grpc_listen_port: 0

positions:
  filename: /logs/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /logs/info.log
          log_level: "info"
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /logs/error.log
          log_level: "error"
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /logs/warning.log
          log_level: "warning"