definitions:
  request.ReqReissue:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  request.ReqRequestPassword:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.ReqSignin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.ReqSignup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  request.ReqValidatePassword:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  response.ResGetUser:
    properties:
      birth:
        type: string
      sex:
        type: string
    type: object
  response.ResReissue:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  response.ResSignin:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /v0.1/auth/logout:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 로그아웃 하기
      tags:
      - auth
  /v0.1/auth/password/request:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: email
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqRequestPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 비밀번호 변경 요청
      tags:
      - auth
  /v0.1/auth/password/validate:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: email, password, code
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqValidatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 비밀번호 변경 검증
      tags:
      - auth
  /v0.1/auth/signin:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResSignin'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 로그인
      tags:
      - auth
  /v0.1/auth/signup:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이름, 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 회원 가입
      tags:
      - auth
  /v0.1/auth/token/reissue:
    put:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 액세스 토큰, 리프레시 토큰
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqReissue'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResReissue'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 액세스 토큰 재발급
      tags:
      - auth
  /v0.1/users/check:
    get:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResGetUser'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 유저 프로필 가져오기
      tags:
      - user
swagger: "2.0"
